config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "profiles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user 
  has_one_attached :image

  validates :gender ,inclusion:{in:%w[m f]}
  validates :matching_gender,inclusion:{in:%w[m f]}
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user= Current.user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy!

    respond_to do |format|
      format.html { redirect_to profiles_path, status: :see_other, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.expect(profile: [ :gender, :matching_gender, :city, :age, :matching_min_age, :matching_max_age, :image, :user_id, :description, :display_name ])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Linder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.css" %>
  </head>

  <body>
     <% if Current.user.present? %>
  <div class="container mx-auto mt-28 px-5 flex">
  <div>
  <%= Current.user.email_address %>
  </div>
  </div>
  <%end%>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, class: "contents") do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul class="list-disc ml-6">
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :gender, "Gender ⚥"%>
    <%= form.select :gender, {options:[["Male ♂","m"],["Female ♀","f"]]}%>
  </div>

  <div class="my-5">  
    <%= form.label :matching_gender, "Matching gender ⚥" %>
    <%# <%= form.text_field :matching_gender, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": profile.errors[:matching_gender].none?, "border-red-400 focus:outline-red-600": profile.errors[:matching_gender].any?}] %> 
 <%= form.select :matching_gender, {options:[["Male ♂","m"],["Female ♀","f"]]}%>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.text_field :city, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": profile.errors[:city].none?, "border-red-400 focus:outline-red-600": profile.errors[:city].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :age %>
    <%= form.number_field :age, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": profile.errors[:age].none?, "border-red-400 focus:outline-red-600": profile.errors[:age].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :matching_min_age %>
    <%= form.number_field :matching_min_age, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": profile.errors[:matching_min_age].none?, "border-red-400 focus:outline-red-600": profile.errors[:matching_min_age].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :matching_max_age %>
    <%= form.number_field :matching_max_age, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": profile.errors[:matching_max_age].none?, "border-red-400 focus:outline-red-600": profile.errors[:matching_max_age].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": profile.errors[:image].none?, "border-red-400 focus:outline-red-600": profile.errors[:image].any?}] %>
  </div>

 

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": profile.errors[:description].none?, "border-red-400 focus:outline-red-600": profile.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :display_name %>
    <%= form.text_field :display_name, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": profile.errors[:display_name].none?, "border-red-400 focus:outline-red-600": profile.errors[:display_name].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Gender:</strong>
    <%= profile.gender %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Matching gender:</strong>
    <%= profile.matching_gender %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= profile.city %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Age:</strong>
    <%= profile.age %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Matching min age:</strong>
    <%= profile.matching_min_age %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Matching max age:</strong>
    <%= profile.matching_max_age %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Image:</strong>
    <%= link_to profile.image.filename, profile.image if profile.image.attached? %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= profile.user_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= profile.description %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Display name:</strong>
    <%= profile.display_name %>
  </p>
</div>

app/views/profiles/edit.html.erb
<% content_for :title, "Editing profile" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing profile</h1>

  <%= render "form", profile: @profile %>

  <%= link_to "Show this profile", @profile, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to profiles", profiles_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/profiles/index.html.erb
<% content_for :title, "Profiles" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Profiles</h1>
    <%= link_to "New profile", new_profile_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="profiles" class="min-w-full">
    <% if @profiles.any? %>
      <% @profiles.each do |profile| %>
        <%= render profile %>
        <p>
          <%= link_to "Show this profile", profile, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No profiles found.</p>
    <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<% content_for :title, "New profile" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New profile</h1>

  <%= render "form", profile: @profile %>

  <%= link_to "Back to profiles", profiles_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/profiles/show.html.erb
<% content_for :title, "Showing profile" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing profile</h1>

  <%= render @profile %>

  <%= link_to "Edit this profile", edit_profile_path(@profile), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to profiles", profiles_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this profile", @profile, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>